name: "Run Tests"

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.0]

    name: PHP${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Create Environment file and generate app key
        run: |
          cp .env.example .env

          php artisan key:generate

      - name: Create database and run migration
        run: |
          touch database/hydra.sqlite
          php artisan migrate
          php artisan db:seed

      - name: Execute tests
        run: vendor/bin/phpunit
